/**
 * ParsedProject-shaped rows for VITE_DEV_DUMMY_DATA local UI review.
 * Keep owner/repo aligned with gitlurker/backend/fixtures/dev_api_samples.json.
 */

const now = Date.now();

/** @returns {string} ISO date `days` ago */
function daysAgo(days) {
  return new Date(now - days * 86400_000).toISOString();
}

/** @returns {import('./parse.js').ParsedProject[]} */
export function getDevDummyProjects() {
  return [
    {
      owner: "demo-org",
      repo: "sample-repo",
      name: "sample-repo",
      description: "Demo repo — release tracking",
      category: "bitcoin",
      subcategory: "wallet",
      tracking_mode: "release",
      web: "",
      clone: "",
      release_version: "v1.2.0",
      release_date_iso: daysAgo(3),
      tag_name: null,
      tag_date_iso: null,
      commit_sha: null,
      commit_date_iso: null,
      commit_author: null,
      stars: 10,
      forks: 2,
      open_issues: 1,
      stale: false,
      _created_at: 1,
    },
    {
      owner: "demo-org",
      repo: "legacy-app",
      name: "legacy-app",
      description: "Old activity — >365d recency band",
      category: "bitcoin",
      subcategory: "protocol",
      tracking_mode: "tag",
      web: "",
      clone: "",
      release_version: null,
      release_date_iso: null,
      tag_name: "v0.9",
      tag_date_iso: daysAgo(400),
      commit_sha: null,
      commit_date_iso: null,
      commit_author: null,
      stars: 3,
      forks: 0,
      open_issues: 0,
      stale: false,
      _created_at: 2,
    },
    {
      owner: "demo-org",
      repo: "stale-repo",
      name: "stale-repo",
      description: "Stale / invalid listing",
      category: "nostr",
      subcategory: "relay",
      tracking_mode: "commit",
      web: "",
      clone: "",
      release_version: null,
      release_date_iso: null,
      tag_name: null,
      tag_date_iso: null,
      commit_sha: "abcdef1234567890",
      commit_date_iso: daysAgo(30),
      commit_author: "bot",
      stars: 0,
      forks: 0,
      open_issues: 0,
      stale: true,
      _created_at: 3,
    },
    {
      owner: "demo-org",
      repo: "skills-demo",
      name: "skills-demo",
      description: "AI skills subcategory icon",
      category: "ai",
      subcategory: "skills",
      tracking_mode: "commit",
      web: "",
      clone: "",
      release_version: null,
      release_date_iso: null,
      tag_name: null,
      tag_date_iso: null,
      commit_sha: "1111111",
      commit_date_iso: daysAgo(10),
      commit_author: "dev",
      stars: 1,
      forks: 0,
      open_issues: 0,
      stale: false,
      _created_at: 4,
    },
    {
      owner: "nostr",
      repo: "ndk",
      name: "ndk",
      description: "≤14d activity band",
      category: "nostr",
      subcategory: "client",
      tracking_mode: "release",
      web: "",
      clone: "",
      release_version: "2.0.0",
      release_date_iso: daysAgo(9),
      tag_name: null,
      tag_date_iso: null,
      commit_sha: null,
      commit_date_iso: null,
      commit_author: null,
      stars: 50,
      forks: 12,
      open_issues: 4,
      stale: false,
      _created_at: 5,
    },
    {
      owner: "acme",
      repo: "layer-node",
      name: "layer-node",
      description: "Layer2 node sample",
      category: "layer2",
      subcategory: "node",
      tracking_mode: "release",
      web: "",
      clone: "",
      release_version: "0.5.1",
      release_date_iso: daysAgo(60),
      tag_name: null,
      tag_date_iso: null,
      commit_sha: null,
      commit_date_iso: null,
      commit_author: null,
      stars: 8,
      forks: 1,
      open_issues: 0,
      stale: false,
      _created_at: 6,
    },
    {
      owner: "demo-org",
      repo: "mcp-server",
      name: "mcp-server",
      description: "Model Context Protocol tools server (MCP Tools row)",
      category: "ai",
      subcategory: "mcp",
      tracking_mode: "release",
      web: "",
      clone: "",
      release_version: "mcp-tools@0.8.0",
      release_date_iso: daysAgo(2),
      tag_name: null,
      tag_date_iso: null,
      commit_sha: null,
      commit_date_iso: null,
      commit_author: null,
      stars: 24,
      forks: 4,
      open_issues: 2,
      stale: false,
      _created_at: 7,
    },
    {
      owner: "another-org",
      repo: "widget-app",
      name: "widget-app",
      description: "Owner page + long semver-style version column",
      category: "bitcoin",
      subcategory: "development",
      tracking_mode: "release",
      web: "",
      clone: "",
      release_version: "2026.3.1+fcs",
      release_date_iso: daysAgo(5),
      tag_name: null,
      tag_date_iso: null,
      commit_sha: null,
      commit_date_iso: null,
      commit_author: null,
      stars: 15,
      forks: 3,
      open_issues: 1,
      stale: false,
      _created_at: 8,
    },
    {
      owner: "another-org",
      repo: "payment-kit",
      name: "payment-kit",
      description: "Second repo under another-org — payments + beta tag in Version column",
      category: "bitcoin",
      subcategory: "payments",
      tracking_mode: "tag",
      web: "",
      clone: "",
      release_version: null,
      release_date_iso: null,
      tag_name: "v12.0.0-beta.2",
      tag_date_iso: daysAgo(12),
      commit_sha: null,
      commit_date_iso: null,
      commit_author: null,
      stars: 99,
      forks: 11,
      open_issues: 6,
      stale: false,
      _created_at: 9,
    },
  ];
}
